name: "Run webhook"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every minute

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute webhook for netlify deployment
        run: echo "testing every 15 minute"
